### ISSUE TITLE
Ubuntu 15.04 (vivid) is released

### ISSUE THREAD

**Issue by kropp** [achaphiv/ppa-fonts#11]
Could you please support it too? Both JDK 7 & 8.

**Comment by achaphiv** [comment]
Building now.

**Comment by gisphm** [comment]
Please build both `freetype` and `fontconfig-infinality` for ubuntu vivid.

**Comment by kropp** [comment]
@achaphiv Thanks! Works great!

**Comment by anaturinbor** [comment]
Yes, please add fontconfig-infinality support for 15.04.
