### ISSUE TITLE
build jdk8 for Trusty (14.04LTS)

### ISSUE THREAD

**Issue by bl4ckn0de** [achaphiv/ppa-fonts#14]
https://github.com/achaphiv/ppa-fonts/issues/9#issuecomment-98431559

**Comment by achaphiv** [comment]
Building now with the package from https://launchpad.net/~openjdk-r/+archive/ubuntu/ppa

**Comment by achaphiv** [comment]
Packages have been built for a while now.

**Comment by ysolis** [comment]
the packages are updated to 8u72 in https://launchpad.net/~openjdk-r/+archive/ubuntu/ppa repo for trusty from December (the same version in xenial alpha 1 now)

but in PPA repo (https://launchpad.net/~no1wantdthisname/+archive/ubuntu/openjdk-fontfix)  for trusty, is not updated, continue to be 8u45-b14-1~14.04ppa1

**Comment by achaphiv** [comment]
Building now.
You could have made a new ticket, by the way.

**Comment by ysolis** [comment]
ok noted ...
