### ISSUE TITLE
Chrome UI huge after installing fonts

### ISSUE THREAD

**Issue by MichaelHindley** [achaphiv/ppa-fonts#15]
![image](https://cloud.githubusercontent.com/assets/1016639/8081340/402742e6-0f74-11e5-88e8-e040bdf3b13c.png)

After installing the fonts, Chrome's UI got several times bigger. This is how it looks by default, it is not "zoomed in" and there are no extensions that would interfere. Is this related to dpi in some way, is there any config that can be changed for this? Other browsers and programs look the same as always, as far as I can tell, this affects only Chrome.

**Comment by achaphiv** [comment]
Despite the lack of comments, I've been on the lookout for this issue.
I haven't seen it in over a year.
No else has mentioned it either, so I can only assume this is a special snowflake.
Thus, I'm going to close.
