### ISSUE TITLE
libfreetype update

### ISSUE THREAD

**Issue by mpalourdio** [achaphiv/ppa-fonts#17]
Hello,

Freetype has been updated. (https://launchpad.net/ubuntu/+source/freetype/2.5.2-2ubuntu3.1) Unfortunately, this update broke infinality during an automatic update of my system.

Would you mind updating your ppa ? Or is there a way I can simply fix it ?

Thanks by advance.

**Comment by sedyshev-a** [comment]
+1 for this, ubuntu 14.04.
Need fix.

**Comment by achaphiv** [comment]
Updated packages have been built and published.

**Comment by mpalourdio** [comment]
Worked like a charm, many thanks !
