### ISSUE TITLE
Support for Mac OS X

### ISSUE THREAD

**Issue by nhahv** [achaphiv/ppa-fonts#19]
Hi.
This patch work perfectly on my ubuntu.
Thanks a lot.
Could you buid somthing like this for Mac OS X. I'am using Apple JDK 1.6 with Intellij IDEA, but it quiet slow and lag. 
Run with Open JDK 7 or 8 is faster. But font rendering is ugly. Help us plz.

**Comment by achaphiv** [comment]
Sorry, but I don't use mac. I wouldn't know where to begin.
