### ISSUE TITLE
Support for Ubuntu 15.10

### ISSUE THREAD

**Issue by kalinichenko88** [achaphiv/ppa-fonts#20]
openjdk-fontfix ppa does not work on last Ubuntu

**Comment by ntvsx193** [comment]
+1

**Comment by achaphiv** [comment]
Building packages.

**Comment by chripede** [comment]
openjdk-8 is not available for 15.10. Looks like the build failed. Can you fix it?

**Comment by achaphiv** [comment]
Yeah, I'm attempting to fix it.
