### ISSUE TITLE
Cannot install jdk

### ISSUE THREAD

**Issue by Nasreddine** [achaphiv/ppa-fonts#26]
After I added the fix package, I tried to install jdk. I've got this message:

The following packages have unmet dependencies:
 openjdk-7-jdk : Depends: openjdk-7-jre (= 7u95-2.6.4-1ppa1)
E: Unable to correct problems, you have held broken packages.

**Comment by achaphiv** [comment]
This looks like Xenial?

It appears to be there.

https://launchpad.net/~no1wantdthisname/+archive/ubuntu/openjdk-fontfix/+files/openjdk-7-jre_7u95-2.6.4-1ppa1_amd64.deb

Maybe try a `apt-get -f install`?

**Comment by achaphiv** [comment]
Looks like `tzdata` went missing.

http://askubuntu.com/questions/795901/what-happened-to-tzdata-java-in-xenial-16-04

**Comment by achaphiv** [comment]
Well, I'm going to close this because it's more of a Ubuntu problem.
Sadly, it looks like it's only going to be openjdk-8 going forward.
