### ISSUE TITLE
Please incorporate latest version from bohoomil

### ISSUE THREAD

**Issue by haizaar** [achaphiv/ppa-fonts#27]
Can you please sync up to the latest code from bohoomil and update the PPA?

P.S. I enjoy your packages for many years already - many thanks for your work! It truly makes my desktop shine.

P.P.S. Readme does not mention that one also needs to install freetype from the PPA. Yet, this is crucial. Is this intentional?

**Comment by achaphiv** [comment]
When last I checked, the bohoomil's patch being used in this repo was the last working version for freetype 2.6.1.

Freetype 2.6.4+ has a new font hinting mode, so maybe I'll try that instead.

**Comment by achaphiv** [comment]
> P.P.S. Readme does not mention that one also needs to install freetype from the PPA. Yet, this is crucial. Is this intentional?

Ah, yeah I figured it was covered by the

```
sudo apt-get upgrade
```

I can explicitly mention it though.

**Comment by achaphiv** [comment]
Updated to freetype 2.6.5 with a variant of bohoomil's patch. Also patched cairo.

I have to update fontconfig, but fonts look okay even without it. So closing for now.

**Comment by haizaar** [comment]
I noticed you've bumped it to freetype 2.7. Thanks! Works fine.

I did a side by side comparison of how fonts look on the same web pages on Kubuntu 14.04 and Ubuntu 16.04 (both with infinality enabled), same version of Chromium 52.x. Most of the pages, e.g. gmail, google search, look the same, except for the Github, where the difference is quite notable. Have a look at the two screenshots below. Do you have an idea why is that so?

16.04 - Release title is very heavy, "Releases"  "Tags" and "Archive content" words are smudged.
![image](https://cloud.githubusercontent.com/assets/58201/18418211/dae9df38-784a-11e6-8e93-5caacc79b670.png)

14.04 - Fonts are much lighter, especially in release title and "Archive content". I've noticed that in 14.04 Chrome uses subpixel rendering for those (colorful blur), while in 16.04 - only hinting (same-color shade).
![image](https://cloud.githubusercontent.com/assets/58201/18418241/37f1c4fc-784b-11e6-8f6b-529baf0a636d.png)

**Comment by achaphiv** [comment]
Hm, I also patched cairo, so that may be causing it. Try downgrading it.

**Comment by haizaar** [comment]
That was also before upgrade (I.e. with packages of your repo at the time
of bug posting). New packages improved hinting - just a bit, only seen
through magnification - but sibpixel rendering still does not come up. Any
other ideas?

**Comment by achaphiv** [comment]
Try removing `fontconfig-infinality`.

Here's what I'm seeing in firefox:
![screenshot from 2016-09-11 14-58-58](https://cloud.githubusercontent.com/assets/678337/18419757/55f234c0-7830-11e6-8224-5d733a22907d.png)

**Comment by haizaar** [comment]
I've got interesting discovery here: when I'm logged in into GitHub, fonts on its pages look great, but when I'm logged out (or in anonymous window) they look awful. It sounds crazy, but I've verified it both in FF and Chrome, both in 16.04 and 14.04. Weird.

Here are screenshots from 16.04, with latest fontconfig-infinality and freetype from your repo.

FF logged in
![ff-logged-in](https://cloud.githubusercontent.com/assets/58201/18428845/00d40c9e-78d9-11e6-9cf6-46a4d6b2f7d5.png)

FF logged out
![ff-logged-out](https://cloud.githubusercontent.com/assets/58201/18428856/16b26e2a-78d9-11e6-9a48-dfc985b76be6.png)

Chrome logged in
![chromium-logged-in](https://cloud.githubusercontent.com/assets/58201/18428866/22bfe594-78d9-11e6-817f-7e71f2005f8f.png)

Chrome logged out
![chromium-logged-out](https://cloud.githubusercontent.com/assets/58201/18428875/28d5e53c-78d9-11e6-9a5e-f06f2afa79fc.png)

**Comment by haizaar** [comment]
BTW, without fontconfig-infinality it behaves the same, and pixel-by-pixel comparison revealed no difference between with and w/o fontconfig-infinatlity, at least this specific GitHub page.

**Comment by achaphiv** [comment]
It turns out 2.7 was broken. As mentioned in #28. Try the latest (2.7-0ubuntu0ppa4)

**Comment by haizaar** [comment]
Yes, the latest 2.7-0ubuntu0ppa4 added back support for fontconfig-infinality. There still weird issues about fonts looking different on GitHub whether you are logged in or logged out, but they look gorgeous everywhere else (not only browsers), so I can live with it.

Thank you very much for your work and for your help!
