### ISSUE TITLE
Switch back to infinality (probably bohoomil's patches) instead of freetype 2.6.4's new engine?

### ISSUE THREAD

**Issue by achaphiv** [achaphiv/ppa-fonts#28]
I recently updated the Xenial (16.04) package to freetype 2.6.5 and enabled the new hinting engine.

From what I've seen thus far, it's better than the default rendering.

Whether it's worse than infinality remains to be seen. If anyone thinks rendering has gotten worse, post here.

**Comment by squallliu** [comment]
It looks worse on my computer.
Hope to return to the old version or provide the old version download.

**Comment by squallliu** [comment]
Rendering the effect is worse than the old version, because the fontconfig is not updated?
Hope to return the old version or provide the old version download.

**Comment by achaphiv** [comment]
Hmm, which version are you on? I messed up packaging.

* 2.6.5-0ubuntu0ppa6 = freetype's new engine
* 2.6.5-0ubuntu0ppa7 = barebones infinality version (I think)
* 2.6.5-0ubuntu0ppa8 = freetype's new engine (again)

**Comment by TiZ-EX1** [comment]
I didn't know not using infinality was an option? I thought infinality was the entire point of this repo. I can't stand regular freetype artificial emboldening, the X-only is much better. I know I've lost infinality somehow when I start seeing ugly bold fonts.

**Comment by squallliu** [comment]
All versions of the bold is too bold，how to improve?

**Comment by TiZ-EX1** [comment]
All versions? I just know that by default, infinality uses X-only emboldening that also doesn't increase character widths. That behavior looks beautiful to me so that's all I'm after.

**Comment by squallliu** [comment]
![image](https://cloud.githubusercontent.com/assets/585678/18371719/376eac36-7669-11e6-908a-f07ad9a97f5c.png)
![image](https://cloud.githubusercontent.com/assets/585678/18371722/4a19bd76-7669-11e6-9aee-c55c14003311.png)

**Comment by TiZ-EX1** [comment]
With ppa7, try opening a terminal, doing `export INFINALITY_FT_USE_VARIOUS_TWEAKS=true`, and running an application with that.

**Comment by achaphiv** [comment]
ppa8 looks okay to me:
![ppa8](https://cloud.githubusercontent.com/assets/678337/18376127/064772b2-762a-11e6-87f0-66bc601eb3c1.png)

It looks like you're using the Ubuntu font, and that still looks okay to me:
![ppa8-ubuntu](https://cloud.githubusercontent.com/assets/678337/18376149/573900f0-762a-11e6-85d3-416fb3cc6796.png)

However, I'll make a ppa9 with bohoomil's infinality patch again just to compare.

**Comment by squallliu** [comment]
ppa10 looks perfect.
Thank you for hard work.
![image](https://cloud.githubusercontent.com/assets/585678/18376940/f56ad7d8-7695-11e6-9567-fd2db3b4322b.png)
![image](https://cloud.githubusercontent.com/assets/585678/18376965/3a629dda-7696-11e6-90eb-32efc33cc012.png)

**Comment by TiZ-EX1** [comment]
Yessss, love that X-only emboldening. Thank you so much!

**Comment by greatquux** [comment]
Version 2.7 offers even more control since it allows compilation of both the old code and the new code and the ability to control rendering at runtime using the FREETYPE_PROPERTIES environment variable (see https://sourceforge.net/projects/freetype/files/freetype2/2.7/).

**Comment by TiZ-EX1** [comment]
That would be great if we could have both. There are a lot of desirable behaviors that are only in infinality. Despite the fact that the last version looked pretty good, it'd be incomplete without them.

**Comment by achaphiv** [comment]
I've built `2.7-0ubuntu0ppa3`.

**Comment by TiZ-EX1** [comment]
I can't find any documentation on what properties are actually available to change.

**Comment by achaphiv** [comment]
Hmm, I'm not seeing a difference with the example listed in the release notes.

http://git.savannah.gnu.org/cgit/freetype/freetype2.git/tree/include/freetype/config/ftoption.h#n78

mentions

* http://git.savannah.gnu.org/cgit/freetype/freetype2.git/tree/include/freetype/ftautoh.h
* http://git.savannah.gnu.org/cgit/freetype/freetype2.git/tree/include/freetype/ftcffdrv.h

Just search for `FT_Property_Set`.

**Comment by greatquux** [comment]
In addition to enabling that, you also have to compile both interpreters. TT_CONFIG_OPTION_SUBPIXEL_HINTING must be defined as '3' so that both interpreters are compiled in and available at runtime.

________________________________

**Comment by achaphiv** [comment]
The patch already does that

~~~
#define TT_CONFIG_OPTION_SUBPIXEL_HINTING  ( 1 | 2 )
~~~

**Comment by squallliu** [comment]
The same configuration, 2.7 looks good, but worse than the previous version.
2.6.5 ppa10
![image](https://cloud.githubusercontent.com/assets/585678/18421380/6351dc6a-78bc-11e6-9f10-33b272781fa6.png)
2.7 ppa3
![image](https://cloud.githubusercontent.com/assets/585678/18421384/78566036-78bc-11e6-91a8-aa7108fa3eb4.png)

**Comment by achaphiv** [comment]
I don't know how you (and many others) get such different results. Are you guys using custom fontconfig settings?

Right now I'm at

* freetype 2.7-0ubuntu0ppa3
* cairo 1.14.6-1ubuntu0ppa1
* fontconfig-infinality *NOT INSTALLED*
* No `INFINALITY*` or `FREETYPE*` or `FT_*` environment settings set

**Comment by TiZ-EX1** [comment]
@squallliu How'd you re-enable X-only emboldening on 2.7?

**Comment by squallliu** [comment]
I use win7 style.
export INFINALITY_FT_FILTER_PARAMS="20 20 30 20 20" environment settings set.
Removed 72 to 74 lines of the 70-forced-synthetic.conf file.

**Comment by TiZ-EX1** [comment]
Okay, but isn't infinality disabled by default on 2.7? How'd you re-enable it?

**Comment by squallliu** [comment]
Sorry, I don't know that.
I just want to bold more smooth.
My configuration referred to this link [https://bbs.archlinux.org/viewtopic.php?id=139543](url).
The configuration of the Firefox does not work, bold ugly.

**Comment by squallliu** [comment]
@achaphiv INFINALITY* environment variables do not seem work on 2.7

**Comment by drps** [comment]
May be i've missed some old configurations but 2.6.1 version with fontconfig-infinality looks better than 2.7 without fontconfig-infinality in most cases for me. It will be great if i could enable/config renderer options on 2.7

**Comment by greatquux** [comment]
@achaphiv Did you happen to see the way TT_CONFIG_OPTION_SUBPIXEL_HINTING was defined in the patches from archfan's repository?  For some reason it defines it twice.  

See
https://github.com/archfan/infinality_bundle/blob/acb83b884f46b4c54a5529376592739f929e0fbe/01_freetype2-iu/0002-infinality-2.7-2016.09.09.patch

lines 62 and 63:
+#define TT_CONFIG_OPTION_SUBPIXEL_HINTING  1
+#define TT_CONFIG_OPTION_SUBPIXEL_HINTING  ( 1 | 2 )

**Comment by TiZ-EX1** [comment]
@squallliu, are you positive you haven't used FREETYPE_PROPERTIES or a fontconfig option to disable Y emboldening and advance widths, or better yet, to just turn the infinality renderer back on? One of the huge gains in X-only emboldening is that the i character is discernible from the l character, whereas in the default case, the stem and dot blur together a bit. Setting truetype:interpreter-version=38 in FREETYPE_PROPERTIES seems to do nothing at all.

I really, really want that X-only emboldening, haha.

**Comment by squallliu** [comment]
@TiZ-EX1 No, I only used the INFINALITY_FT_FILTER_PARAMS and force fake bold instead of the font's default bold.

**Comment by achaphiv** [comment]
> @achaphiv Did you happen to see the way TT_CONFIG_OPTION_SUBPIXEL_HINTING was defined in the patches from archfan's repository? For some reason it defines it twice. 

Yeah, I noticed. The 2nd `#define` should just overwrite the first, right?

**Comment by achaphiv** [comment]
There's definitely something wrong with the patch for freetype 2.7, but it's almost entirely the same as 2.6.5.

**Comment by achaphiv** [comment]
Oh, wow I see it.

He forgot to
`#define FT_CONFIG_OPTION_INFINALITY_PATCHSET`
in `ftoption.h`

**Comment by squallliu** [comment]
@achaphiv I have been updated to 2.7 ppa4, the problem has been fixed.

**Comment by greatquux** [comment]
Infinality patchset is working again in 2.7 ppa4.  The FREETYPE_PROPERTIES environment variable still has no effect though, but I think most people prefer the "old" rendering anyway!

**Comment by achaphiv** [comment]
The intent of this issue has been fulfilled. Rendering issues can do in separate issues.

**Comment by achaphiv** [comment]
Surprising, `FREETYPE_PROPERTIES` does cause a visible difference when antialiasing is turned off.

https://github.com/achaphiv/ppa-fonts/issues/29#issuecomment-247732039

**Comment by greatquux** [comment]
Huh., that's surprising as it doesn't seem to have any effect for me (I export version 40, then run the 'waterfall' font demonstration program, then export with version 35 and run waterfall again which starts a new process and they look exactly the same).  I'm also not sure the second #define overwrites the first, but in any case it doesn't really matter for me, as long the Infinality environment variables are respected, all our fonts look great again. :) Thanks for making this PPA and updating it to the latest version (now we can upgrade to 16.10!)
