### ISSUE TITLE
Build for 12.04

### ISSUE THREAD

**Issue by ufovsalien** [achaphiv/ppa-fonts#3]
Hi, I tried to build 14.04 source to 12.04, but build fails with '-02 unknown option.' Building process was really long on atom.
Maybe, you can apply back 12.04 support. Many people use 12.04 (and it has support).

**Comment by cpriego** [comment]
The solution to the superbold fonts with **_any_** openJDK is uninstalling a fonts package:
```
sudo apt-get remove fonts-unfonts-core
```
As established here http://askubuntu.com/a/125619

**Comment by achaphiv** [comment]
Closing since original issue has been resolved. If the superbold thing is still occurring, then that will be a separate issue.
