### ISSUE TITLE
How to enable v40 FreeType interpreter on Ubuntu 16.04 using your PPA?

### ISSUE THREAD

**Issue by kq01526** [achaphiv/ppa-fonts#35]
@achaphiv After installing [your PPA](https://launchpad.net/~no1wantdthisname/+archive/ubuntu/ppa) on Ubuntu 16.04, is there anything else that needs to be done to enable [the new v40 interpreter](https://www.phoronix.com/scan.php?page=news_item&px=FreeType-2.7-Released)?

**Comment by achaphiv** [comment]
I remember I turned it on for #28, but people didn't like the results. I.E. still not as good as infinality.

I vaguely recall it being a compile time flag.

**Comment by kq01526** [comment]
@achaphiv Thanks, so simply installing the PPA should be enough? Is there any way to check which interpreter version is currently being used?

Also, what would I need to set the hinting to? None? Slight? Medium? Full?

When reading through https://www.reddit.com/r/linux/comments/4tb2dt/freetype_27_bringing_directwritecleartypelike/ I get the idea to set hinting to "None" to enable v40? Is that correst?

**Comment by kq01526** [comment]
Okay, so according to https://github.com/achaphiv/ppa-fonts/issues/29#issuecomment-247732039 you can switch between the different interpreters via the command line, by exporting an environment variable.

But v40 should be the default anyway, right? So that should not be necessary when you want v40, right?

**Comment by kq01526** [comment]
Also came across this: https://www.freetype.org/freetype2/docs/reference/ft2-tt_driver.html

**Comment by kq01526** [comment]
Looks like FreeType 2.8.1 adds a new default: https://github.com/achaphiv/ppa-fonts/issues/36

**Comment by pandasauce** [comment]
PPA forces v38 by default. v40 is the default as of 2.7 upstream. If you want v40, you don't need the PPA. In order for it to be configurable at runtime, you need the `( 1 | 2 )` version of [this patch](https://github.com/achaphiv/ppa-fonts/blob/master/ppa/patches-freetype/enable_v38.patch).

**Comment by achaphiv** [comment]
Yep. I initially enabled both v38 and v40, but realized it was pointless. Why use this PPA when you can just use the official packages?

To summarize for anyone else stumbling upon this ticket:

* Interpreter v40 = official support and the default as of v2.7.1(?). The fastest option.
* Interpreter v38 = official support, but not the default. Slower than v40. A.K.A. "infinality-lite".
* Interpreter v35 = official support, legacy engine.
* Infinality custom patches = unofficial 3rd party patches. Slowest option. Looks the best (IMO).

This PPA is currently at option `Interpreter v38`.

I would like to be at option `Infinality custom patches`, but the patches have not been updated for freetype 2.9.x+. See #36.

**Comment by pandasauce** [comment]
@achaphiv your preferred option [is now available for 2.9.1](https://github.com/archfan/infinality_bundle/blob/master/01_freetype2-iu/0001-infinality-2.9.1-2018.06.21.patch). These are the changes you need to build it:

* https://gitlab.com/pandasauce/freetype-builds/tree/2.9.1-infinality/workdir/patches/debian
* https://gitlab.com/pandasauce/freetype-builds/blob/2.9.1-infinality/workdir/build-freetype#L38-90

The line height bugs from FreeType are still around, they were introduced in the upstream FreeType code base somewhere around 2.8, but other than that it works fine.

**Comment by achaphiv** [comment]
Closing this issue since v40 is just the default engine for the regular ubuntu packages.
