### ISSUE TITLE
Enable builds for Artful (17.10)

### ISSUE THREAD

**Issue by funnylookinhat** [achaphiv/ppa-fonts#37]
It looks like the series is enabled, but the only package that is building is `freetype` - I would have expected `fontconfig-infinality` to show up?

https://launchpad.net/~no1wantdthisname/+archive/ubuntu/ppa?field.series_filter=artful

**Comment by achaphiv** [comment]
`fontconfig-infinality` has been gone for a while now.

Note how it also doesn't exist for zesty. I also updated the install instructions to no longer mention it.

The reasoning is in #32.

Specifically: https://github.com/achaphiv/ppa-fonts/issues/32#issuecomment-297676916

**Comment by funnylookinhat** [comment]
Oh yeah I see that now - sorry for the extra bug.  :)
