### ISSUE TITLE
Openjdk 8 missing from repository

### ISSUE THREAD

**Issue by xavier83ar** [achaphiv/ppa-fonts#39]
Today I've updated ubuntu and the openjdk got back to default version, provided by SO's repositories. I researched a bit and find out that the this repository has only packages for openjdk/jre version 7, and there is no packages for version 8. I did a ppa-purge and try to install it again with the same result.

This screenshot of synaptic show what's in the repository:

![seleccion_033](https://user-images.githubusercontent.com/1458700/38566940-55468ffc-3cbb-11e8-9c72-cc1a023a9d03.png)

The SO is Ubuntu 16.04.

**Comment by achaphiv** [comment]
Probably because there's a security update. I'm rebuilding for the latest.

**Comment by xavier83ar** [comment]
it's been fixed.
