### ISSUE TITLE
fontconfig-infinality is missing in Bionic PPA (18.04)

### ISSUE THREAD

**Issue by pandasauce** [achaphiv/ppa-fonts#42]
`fontconfig-infinality` is missing in Bionic PPA. Force installing the `.deb` from Xenial results in 2 things breaking:

1. Line heights for the affected fonts start overlapping, e.g. when opening this page: https://raw.githubusercontent.com/achaphiv/ppa-fonts/master/README.md
2. Unicode symbols disappear in some instances, for example the watch symbol from https://github.com/robbyrussell/oh-my-zsh/blob/master/themes/amuse.zsh-theme will not display in the terminal when using Ubuntu Mono as the terminal font.

The defaults that come in 18.04 are still ugly and nowhere near as good.

**Comment by pandasauce** [comment]
Closing this, my mistake - screwed up the permissions on one of the fonts folder during an upgrade to bionic, that cascaded down and broke a bunch of other things. The .deb from Xenial works fine.

**Comment by achaphiv** [comment]
I suspect this is might be more than just fontconfig.
The *full* infinality patch is currently dead for freetype 2.8.1+.

* Artful uses freetype 2.8.0
* Bionic uses freetype 2.8.1

#36 is somewhat related.

The current Bionic patch enables *v38* (barebones infinality) mode.
As mentioned here: https://www.freetype.org/freetype2/docs/subpixel-hinting.html

Clearly it's not as good as the full infinality patch.
Sadly I haven't seen any updates for 2.8.1 or even the current 2.9.

**Comment by pandasauce** [comment]
The current Bionic patch coupled with the fontconfig package from Xenial does a superb job. Without fontconfig though it is not as good. For example, Ubuntu Mono remains thick and difficult to read without it.

Two things that screwed it up for me after upgrading to Bionic were the emoji font installed by default and my own umask settings making my Windows fonts directory not world-readable. Each corresponds to a list item from my original post.

**Comment by haizaar** [comment]
I second @pandasauce that bionic's patch + fontconfig-infinality packages makes fonts look as great as they did in Xenial :)

It will be great to have fontconfig-infinality package to be available in bionic.

As always - huge thanks for making fonts to look great!
