### ISSUE TITLE
create a build for Ubuntu 19 (disco)

### ISSUE THREAD

**Issue by vladzcloudius** [achaphiv/ppa-fonts#45]
Rendering out of the box is still awful.
Could you, please, create a build for U19 or tell me how I can build it myself.

I upgraded from U18.04 to U19 because of the Gnome and (not that surprisingly) my beautiful Infinality configuration doesn't work anymore.

I'd love to be able to enjoy proper fonts rendering again! ;)

Please, help!

**Comment by vladzcloudius** [comment]
I noticed that there were similar requests in the past.
I have a question: is there any chance to make the Infinality configuration coming from `/etc/profile.d/infinality-settings.sh` working with the stock freetype? 

After reading this: https://www.freetype.org/freetype2/docs/subpixel-hinting.html I understand - there isn't.

Reading this blog left me speechless - who the HECK cares about speed when it comes to fonts rendering these days?!

**Comment by greatquux** [comment]
While I do second the request to rebuild for 19.04, I also think they've made great strides in the last few years with rendering. It may not be as good as a customized infinality config but it's no longer "awful".

**Comment by vladzcloudius** [comment]
@greatquux I may have been exaggerating a little ;)
But I'm on Infinality builds for about 5 years - I'm a spoiled fruit... ;)

**Comment by achaphiv** [comment]
I tried building for `disco`, but it didn't work.

Ah, the joy of debian packaging.

I'll try to fix it this weekend.

**Comment by vladzcloudius** [comment]
@achaphiv Really appreciated! 
Meanwhile I was able to force install the `cosmic` binaries. So far so good ;)

**Comment by achaphiv** [comment]
Alright, give it a shot.

The version says `2.9.1c`, but it's really `2.9.1`.
The packaging structure completely changed in `disco`, so I had to do a workaround.

**Comment by vladzcloudius** [comment]
@achaphiv Thanks a lot! I installation worked smoothly. Looking good so far.
