### ISSUE TITLE
Ubuntu 14.10 support?

### ISSUE THREAD

**Issue by sonicflare** [achaphiv/ppa-fonts#5]
Will new ubuntu be supported?

**Comment by AAlakkad** [comment]
@achaphiv Hello, can you please update to 14.10? or maybe put the build instructions in the readme file. 
I miss this package after upgrading Ubuntu to 14.10.

Thanks!

**Comment by ntvsx193** [comment]
+1

**Comment by sonicflare** [comment]
Guys, just use:

add-apt-repository ppa:no1wantdthisname/ppa

and it is working fine in 14.10

**Comment by AAlakkad** [comment]
You're right, I'm already using infinality on 14.10, but  I meant the OpenJDK with font fix.

**Comment by sonicflare** [comment]
@AAlakkad you can also check TuxJDK
https://code.google.com/p/tuxjdk/
