### ISSUE TITLE
7u75-2.5.4 is available

### ISSUE THREAD

**Issue by dlussky** [achaphiv/ppa-fonts#6]
Just in case someone wants to use build_package script from this repo:
change debuild parameters to something like that 
-b -us -uc -sd -i 
(building only binary package without any signing and stuff)
and comment out dput
Then, change the version in the last line to what you actually have in your repo (for 14.04 it is 7u75-2.5.4-1~trusty1)

*also you'll need to install some dependencies, you'll see the error with all needed packages on the first launch)

**Comment by achaphiv** [comment]
Building packages now.

**Comment by achaphiv** [comment]
Packages successfully built.

**Comment by dlussky** [comment]
That was a long build))
