### ISSUE TITLE
Any plans on building for openjdk 8?

### ISSUE THREAD

**Issue by cpriego** [achaphiv/ppa-fonts#9]
Just as the title says, do you have any plans on building for openjdk 8?

Thanks in advance.

**Comment by achaphiv** [comment]
Yeah I'll build whenever an official package comes out. I believe this will be in 14.10.

**Comment by achaphiv** [comment]
Just built for utopic.

**Comment by cpriego** [comment]
Amazing! Trying it right now.

**Comment by bl4ckn0de** [comment]
do you have any plan to backport this to Trusty LTS support ?

**Comment by achaphiv** [comment]
No, since there's no existing package for trusty.
https://launchpad.net/ubuntu/+source/openjdk-8

**Comment by bl4ckn0de** [comment]
On Sun, May 3, 2015 at 4:43 AM, achaphiv <notifications@github.com> 
wrote:
> No, since there's no existing package for trusty.
> https://launchpad.net/ubuntu/+source/openjdk-8
> 

so do the project is based only in oficial Canonical/Ubuntu source code 
for debs? there exist two PPAs with support for OpenJDK 8 in Trusty. Do 
we can re-use it ?

**Comment by achaphiv** [comment]
I haven't tried myself, but it probably does work.
